const quiz = [
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
    {
        question:"",
        answers:["",""],
    },
];